[package]
name = "rust_learning"
version = "0.1.0"
authors = ["Kasper S. Nielsen (desktop) <au617086@uni.au.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
hacspec = "0.2.0-beta.1"